### ISSUE TITLE
Running lein caribou migrate results in NullPointerException

### ISSUE THREAD

**Issue by Kungi** [caribou/caribou#3]
I am trying to set up an example project as described in the documentation by running 

```
lein new caribou oberon
```

and then 

```
lein caribou migrate resources/config/development.clj
```

This leads to a NullPointerException in caribou.db.adapter.adapter_for

```
ERROR  no current database connection
INFO  Already used these:
nil
INFO   -> migration caribou.migrations.bootstrap started.
Exception in thread "main" java.lang.NullPointerException
        at caribou.db.adapter$adapter_for.invoke(adapter.clj:12)
        at caribou.config$process_config.invoke(config.clj:146)
        at caribou.core$init.invoke(core.clj:15)
        at caribou.migration$migrate.invoke(migration.clj:50)
        at caribou.migration$run_migration.invoke(migration.clj:61)
        at caribou.migration$run_migrations$fn__8594.invoke(migration.clj:80)
        at caribou.migration$run_migrations.doInvoke(migration.clj:67)
        at clojure.lang.RestFn.invoke(RestFn.java:467)
        at user$eval8672.invoke(form-init454657187453232524.clj:1)
        at clojure.lang.Compiler.eval(Compiler.java:6619)
        at clojure.lang.Compiler.eval(Compiler.java:6609)
        at clojure.lang.Compiler.load(Compiler.java:7064)
        at clojure.lang.Compiler.loadFile(Compiler.java:7020)
        at clojure.main$load_script.invoke(main.clj:294)
        at clojure.main$init_opt.invoke(main.clj:299)
        at clojure.main$initialize.invoke(main.clj:327)
        at clojure.main$null_opt.invoke(main.clj:362)
        at clojure.main$main.doInvoke(main.clj:440)
        at clojure.lang.RestFn.invoke(RestFn.java:421)
        at clojure.lang.Var.invoke(Var.java:419)
        at clojure.lang.AFn.applyToHelper(AFn.java:163)
        at clojure.lang.Var.applyTo(Var.java:532)
        at clojure.main.main(main.java:37)
Subprocess failed
```

Can you please help me debug this problem?

**Comment by prismofeverything** [comment]
Ah, you need to specify a project name!

> lein new caribou alphamax

Or 

> lein new caribou oboron

**Comment by Kungi** [comment]
I did that and updated my question to reflect this. I still get the same NullPointerException.

**Comment by prismofeverything** [comment]
What is in your resources/config/development.clj?

**Comment by Kungi** [comment]
Since I did not change anything in the leiningen template my ~/oberon/resources/config/development.clj file contains this:

```
{:logging {:loggers [{:type :stdout :level :debug}
                     ;; {:type :remote :host "beast.local" :level :debug}
                     ;; {:type :file :file "caribou-logging.out" :level :debug}
                     ]}
 :app {:use-database true}
 :cljs {:root "resources/cljs"
        :reload false
        :options {:output-to "resources/public/js/app/oberon.js"
                  :optimizations :whitespace
                  :pretty-print true}}
 :database {:classname    "org.h2.Driver"
            :subprotocol  "h2"
            :protocol     "file"
            :path         "./"
            :database     "oberon_development"
            :host         "localhost"
            :subname      "file:oberon_development"
            :user         "h2"
            :password     ""}
 :controller {:namespace "oberon.controllers" :reload :always}
 :nrepl {:port 44444}
 :cache-templates :never}
```

**Comment by prismofeverything** [comment]
Hmm... works fine for me (of course).  What is your java version?  OS?

Also, what is in your project.clj?

**Comment by prismofeverything** [comment]
Also, what version of lein are you using?

**Comment by noisesmith** [comment]
I just verified that with a cleared .m2/repositories cache, using jdk 1.7, I can bootstrap a site.

```
justin@fuckmonkey:~/oberon$ lein version
Leiningen 2.1.2 on Java 1.7.0_40 Java HotSpot(TM) 64-Bit Server VM
```

**Comment by Kungi** [comment]
```
kungi@Gibbs: lein version
Leiningen 2.3.4 on Java 1.6.0_65 Java HotSpot(TM) 64-Bit Server VM
```

```
project.clj
(defproject oberon "0.13.3"
  :description "The page routing ring handler for caribou"
  :dependencies [[org.clojure/clojure "1.5.1"]
                 [http-kit "2.1.12"]
                 [org.immutant/immutant "1.0.2"]
                 [caribou/caribou-admin "0.13.3"]
                 [caribou/caribou-api "0.13.3"]
                 [schmetterling "0.0.2"]
                 [org.clojure/tools.nrepl "0.2.3"]]
  :plugins [[lein-ring "0.8.6"]
            [caribou/lein-caribou "2.13.2"]
            [lein-cljsbuild "0.3.3"]]
  :jvm-opts ["-agentlib:jdwp=transport=dt_socket,server=y,suspend=n" 
             "-Dclojure.compiler.disable-locals-clearing=true"
             "-Xmx2g" 
             "-XX:MaxPermSize=128m"
             "-XX:MaxInlineSize=0"]
  :source-paths ["src"]
  :resource-paths ["resources/"]
  :min-lein-version "2.0.0"
  :migration-namespace oberon.migrations
  :main oberon.core
  :ring {:handler oberon.core/handler
         :init oberon.core/init
         :port 33333
         :auto-reload? false
         :servlet-name "oberon-frontend"}
  :immutant {:context-path "/"
             :init oberon.immutant/init}
  :cljsbuild {:repl-listen-port 44994
              :builds
              [{:source-paths ["resources/cljs"]
                :compiler {:output-to "resources/public/js/app/oberon.js"
                           :optimizations :whitespace
                           :pretty-print true}}]})
```

```
kungi@Gibbs: java -version
Picked up JAVA_TOOL_OPTIONS:
Picked up _JAVA_OPTIONS: -Denvironment=development
java version "1.6.0_65"
Java(TM) SE Runtime Environment (build 1.6.0_65-b14-462-11M4609)
Java HotSpot(TM) 64-Bit Server VM (build 20.65-b04-462, mixed mode)
```

```
Mac OS 10.9.1
```
