### ISSUE TITLE
Initial Caribou migration failing on heroku deployment

### ISSUE THREAD

**Issue by dparis** [caribou/caribou#4]
I'm following the heroku [deployment instructions](http://caribou.github.io/caribou/docs/deploying.html) and I'm stuck at the step where I have to run the initial migration.

I've applied all of the appropriate heroku credential info to the heroku.clj `:database` map, and I've double-checked that the values are correct. When I run `lein caribou migrate resources/config/heroku.clj` I get the following output:

```
-> Running migrations on config
Listening for transport dt_socket at address: 50757
ERROR  no current database connection
Exception in thread "main" org.postgresql.util.PSQLException: FATAL: password authentication failed for user "*******"
    at org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:291)
    at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:108)
    at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:66)
    at org.postgresql.jdbc2.AbstractJdbc2Connection.<init>(AbstractJdbc2Connection.java:125)
    at org.postgresql.jdbc3.AbstractJdbc3Connection.<init>(AbstractJdbc3Connection.java:30)
    at org.postgresql.jdbc3g.AbstractJdbc3gConnection.<init>(AbstractJdbc3gConnection.java:22)
    at org.postgresql.jdbc4.AbstractJdbc4Connection.<init>(AbstractJdbc4Connection.java:30)
    at org.postgresql.jdbc4.Jdbc4Connection.<init>(Jdbc4Connection.java:24)
    at org.postgresql.Driver.makeConnection(Driver.java:393)
    at org.postgresql.Driver.connect(Driver.java:267)
    at java.sql.DriverManager.getConnection(DriverManager.java:571)
    at java.sql.DriverManager.getConnection(DriverManager.java:187)
    at clojure.java.jdbc$get_connection.invoke(jdbc.clj:177)
    at clojure.java.jdbc$with_connection_STAR_.invoke(jdbc.clj:300)
    at caribou.migration$run_migrations$fn__8970.invoke(migration.clj:67)
    at caribou.migration$run_migrations.doInvoke(migration.clj:67)
    at clojure.lang.RestFn.invoke(RestFn.java:467)
    at user$eval9048.invoke(form-init2474686299645871224.clj:1)
    at clojure.lang.Compiler.eval(Compiler.java:6619)
    at clojure.lang.Compiler.eval(Compiler.java:6609)
    at clojure.lang.Compiler.load(Compiler.java:7064)
    at clojure.lang.Compiler.loadFile(Compiler.java:7020)
    at clojure.main$load_script.invoke(main.clj:294)
    at clojure.main$init_opt.invoke(main.clj:299)
    at clojure.main$initialize.invoke(main.clj:327)
    at clojure.main$null_opt.invoke(main.clj:362)
    at clojure.main$main.doInvoke(main.clj:440)
    at clojure.lang.RestFn.invoke(RestFn.java:421)
    at clojure.lang.Var.invoke(Var.java:419)
    at clojure.lang.AFn.applyToHelper(AFn.java:163)
    at clojure.lang.Var.applyTo(Var.java:532)
    at clojure.main.main(main.java:37)
Subprocess failed
```

I've tried connecting to heroku using psql directly with the same credentials and it seems to connect just fine.

Lein version is 2.3.4 on Java 1.7.0_51 Java HotSpot(TM) 64-Bit Server VM.

Any ideas? Maybe something changed on the heroku side? Or maybe the docs are out of date? I was interested in exploring caribou for this project, but I need to get started on it ASAP so I'll have to use another framework if I can't figure this out soon.

**Comment by prismofeverything** [comment]
Hi Dylan,

The stacktrace is saying the password is either missing or wrong.  Can you paste in your heroku.clj as well?  I just want to make sure it is well formed.  Also, is the password exactly as it appears from the result of your 

>  heroku pg:credentials DATABASE

command?

**Comment by dparis** [comment]
Sure, I'll post my config first thing tomorrow. I've only modified the values in the `database` map, otherwise it's just the defaults generated by `lein new caribou ...`.

As for whether the password is correct, I am very confident that it is. Based on the exception thrown, checking the password was the first thing I thought to try, so I logged in using psql successfully and then copy-pasted from that command directly into the heroku.clj file. Still got the error.

**Comment by prismofeverything** [comment]
I believe you could also get that error if the username is incorrect?  I just went through the heroku process again and everything seems to be working.  I suspect something about your config map is slightly off (keyword not a keyword, value not a string, extra parens etc).

**Comment by dparis** [comment]
Ugh, fighting other fires all day. Here's my heroku config, redacted:

``` clojure
{:logging {:loggers [{:type :stdout :level :warn}]}
 :database {:classname    "org.postgresql.Driver"
            :subprotocol  "postgresql"
            :database     "****"
            :host         "****"
            :port         5562
            :user         "****"
            :password     "****"
            :ssl          true
            :sslfactory   "org.postgresql.ssl.NonValidatingFactory"}
 :controller {:namespace "foobar.controllers" :reload :never}
 :cache-templates :always}
```

Pretty sure it's validly formatted. I created a new project, diffed the defaults with my current file, and it only showed the connection info lines had changed. Of those, only the values in the strings had changed, or in the case of the `:port` key, the integer.

**Comment by prismofeverything** [comment]
Hmm… everything looks fine, interesting about your port though.  For me the given port was 5432.  Have you checked that against the port in the connection URL given by

> heroku pg:credentials DATABASE

?

**Comment by dparis** [comment]
Yup, definitely. Just double-checked again. I would imagine that the port assigned is random within a range.

Are you currently at Clojure/West? If so, maybe we could meet up and debug in person? Otherwise, I can look into this some more later this week.

Thanks for checking on this. I hope I'm able to get caribou working for me, looks pretty good!
