### ISSUE TITLE
Admin login not working

### ISSUE THREAD

**Issue by gordonro-zz** [caribou/caribou#5]
Using versions: Leiningen 2.3.4 on Java 1.7.0_17 Java HotSpot(TM) 64-Bit Server VM

Just tired the example installation using
lein new caribou taiga
cd taiga
lein caribou migrate resources/config/development.clj

The project ran OK, but when I tried to go to the admin webpage is got this Error:

INFO :nrepl Starting nrepl server on port :44444
Caribou running on port 33333

http://localhost:33333/_admin/login
Page reported:
CARIBOU
500

Terminal error trace:

ERROR  java.lang.Exception: invalid caribou model::role
ERROR    |--> caribou.model$gather.invoke(model.clj:295)
ERROR    |--> caribou.model$pick.invoke(model.clj:324)
ERROR    |--> caribou.admin.rights$all_permissions.invoke(rights.clj:24)
ERROR    |--> caribou.admin.rights$with_permissions$fn__14924.invoke(rights.clj:104)
ERROR    |--> caribou.admin.core$provide_helpers$fn__15109.invoke(core.clj:85)
ERROR    |--> caribou.admin.core$user_required$fn__15096.invoke(core.clj:62)
ERROR    |--> caribou.admin.core$get_models$fn__15101.invoke(core.clj:75)
ERROR    |--> polaris.core$router$fn__11099.invoke(core.clj:134)
ERROR    |--> caribou.app.handler$handler$fn__14749.invoke(handler.clj:53)
ERROR    |--> caribou.app.helpers$wrap_helpers$fn__11933.invoke(helpers.clj:173)
ERROR    |--> ring.middleware.reload$wrap_reload$fn__1112.invoke(reload.clj:18)
ERROR    |--> ring.middleware.file$wrap_file$fn__784.invoke(file.clj:35)
ERROR    |--> ring.middleware.resource$wrap_resource$fn__845.invoke(resource.clj:24)
ERROR    |--> ring.middleware.file_info$wrap_file_info$fn__830.invoke(file_info.clj:64)
ERROR    |--> ring.middleware.content_type$wrap_content_type$fn__2346.invoke(content_type.clj:26)
ERROR    |--> ring.middleware.head$wrap_head$fn__770.invoke(head.clj:26)
ERROR    |--> lichen.core$wrap_lichen$fn__3074.invoke(core.clj:118)
ERROR    |--> caribou.app.middleware$wrap_path_info$fn__11845.invoke(middleware.clj:55)
ERROR    |--> caribou.app.middleware$wrap_xhr_request$fn__11836.invoke(middleware.clj:37)
ERROR    |--> ring.middleware.json$wrap_json_params$fn__512.invoke(json.clj:33)
ERROR    |--> ring.middleware.multipart_params$wrap_multipart_params$fn__681.invoke(multipart_params.clj:107)
ERROR    |--> ring.middleware.keyword_params$wrap_keyword_params$fn__931.invoke(keyword_params.clj:32)
ERROR    |--> ring.middleware.nested_params$wrap_nested_params$fn__897.invoke(nested_params.clj:70)
ERROR    |--> ring.middleware.params$wrap_params$fn__709.invoke(params.clj:58)
ERROR    |--> caribou.app.cljs$wrap_cljs$fn__14347.invoke(cljs.clj:36)
ERROR    |--> caribou.app.handler$wrap_caribou$fn__14731$fn__14732.invoke(handler.clj:22)
ERROR    |--> clojure.java.jdbc$with_connection_STAR_.invoke(jdbc.clj:302)
ERROR    |--> caribou.app.handler$wrap_caribou$fn__14731.invoke(handler.clj:19)
ERROR    |--> ring.middleware.session$wrap_session$fn__2297.invoke(session.clj:85)
ERROR    |--> ring.middleware.cookies$wrap_cookies$fn__2178.invoke(cookies.clj:171)
ERROR    |--> clojure.lang.Var.invoke(Var.java:415)
ERROR    |--> org.httpkit.server.HttpHandler.run(RingHandler.java:91)
ERROR    |--> java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
ERROR    |--> java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
ERROR    |--> java.util.concurrent.FutureTask.run(FutureTask.java:166)
ERROR    |--> java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
ERROR    |--> java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
ERROR    |--> java.lang.Thread.run(Thread.java:722)
Sat Jun 14 22:30:00 EST 2014 [worker-3] ERROR - GET /_admin
java.lang.NullPointerException
    at java.io.FilterInputStream.read(FilterInputStream.java:133)
    at java.io.FilterInputStream.read(FilterInputStream.java:107)
    at org.httpkit.HttpUtils.readAll(HttpUtils.java:293)
    at org.httpkit.HttpUtils.bodyBuffer(HttpUtils.java:95)
    at org.httpkit.HttpUtils.HttpEncode(HttpUtils.java:429)
    at org.httpkit.server.HttpHandler.run(RingHandler.java:101)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
    at java.util.concurrent.FutureTask.run(FutureTask.java:166)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:722)

**Comment by noisesmith** [comment]
cannot reproduce with Leiningen 2.4.0 on Java 1.8.0_05 Java HotSpot(TM) 64-Bit Server VM

the up to date version of the caribou template should bootstrap the :role model properly (though we have seen errors in that function that are rooted in some other deeper problem). Essentially, the with-permissions function that checks your role is the first point where the code just gives up if the models are not available.

**Comment by noisesmith** [comment]
Also, using a relatively new computer, where this is the first install of lein, so a fresh checkout with no profiles.clj should replicate this behavior with all versions up to date.

lein new created deps for caribou-admin 0.14.0 and caribou-api 0.14.0

**Comment by noisesmith** [comment]
can you check if you can replicate the following repl session via `lein repl`? :

```
taiga.core=> (require '[taiga.boot :as boot] '[caribou.model :as model] '[caribou.core :as caribou])
nil
taiga.core=> (def config (boot/boot))
#'taiga.core/config
taiga.core=> (caribou/with-caribou config (model/pick :model {:where {:slug "role"}}))
{:slug "role", :position 16, :display nil, :join-model false, :localized false, :name "Role", :locked true, :status-id nil, :ancestor-id nil, :searchable false, :uuid "663258ec-c2c1-4096-a4e2-d5926ed173cf", :updated-at #inst "2014-06-14T17:07:35.319000000-00:00", :created-at #inst "2014-06-14T17:07:35.286000000-00:00", :nested false, :abstract false, :id 16, :description "", :status-position 3}
taiga.core=> 
```

**Comment by gordonro-zz** [comment]
Will try, note I'm using OSX Mavericks...

Best regards,

Gordon Oliver

On 15 Jun 2014, at 3:23 am, noisesmith notifications@github.com wrote:

can you check if you can replicate the following repl session via lein repl?
:

taiga.core=> (require '[taiga.boot :as boot] '[caribou.model :as
model] '[caribou.core :as caribou])
nil
taiga.core=> (def config (boot/boot))
#'taiga.core/config
taiga.core=> (caribou/with-caribou config (model/pick :model {:where
{:slug "role"}}))
{:slug "role", :position 16, :display nil, :join-model false,
:localized false, :name "Role", :locked true, :status-id nil,
:ancestor-id nil, :searchable false, :uuid
"663258ec-c2c1-4096-a4e2-d5926ed173cf", :updated-at #inst
"2014-06-14T17:07:35.319000000-00:00", :created-at #inst
"2014-06-14T17:07:35.286000000-00:00", :nested false, :abstract false,
:id 16, :description "", :status-position 3}
taiga.core=>

**Comment by gordonro-zz** [comment]
Hi Tried to replicate, and got this:

taiga.core=> (require '[taiga.boot :as boot] '[caribou.model :as model] '[caribou.core :as caribou])
nil
taiga.core=> (def config (boot/boot))
DEBUG :INVOKE_MODELS No models table yet!
DEBUG :stacktrace >>> org.postgresql.util.PSQLException: ERROR: relation "model" does not exist
  Position: 15
DEBUG :stacktrace     |--org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2077)
DEBUG :stacktrace     |--org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1810)
DEBUG :stacktrace     |--org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:257)
DEBUG :stacktrace     |--org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:498)
DEBUG :stacktrace     |--org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:386)
DEBUG :stacktrace     |--org.postgresql.jdbc2.AbstractJdbc2Statement.executeQuery(AbstractJdbc2Statement.java:271)
DEBUG :stacktrace     |--clojure.java.jdbc$with_query_results_STAR_.invoke(jdbc.clj:672)
DEBUG :stacktrace     |--caribou.db$query.invoke(db.clj:17)
DEBUG :stacktrace     |--caribou.db$query.invoke(db.clj:14)
DEBUG :stacktrace     |--caribou.model$invoke_models.invoke(model.clj:877)
DEBUG :stacktrace     |--caribou.core$init$fn__10721.invoke(core.clj:18)
DEBUG :stacktrace     |--clojure.java.jdbc$with_connection_STAR_.invoke(jdbc.clj:302)
DEBUG :stacktrace     |--caribou.core$init.invoke(core.clj:16)
DEBUG :stacktrace     |--taiga.boot$boot.invoke(boot.clj:49)
DEBUG :stacktrace     |--clojure.lang.AFn.applyToHelper(AFn.java:159)
DEBUG :stacktrace     |--clojure.lang.AFn.applyTo(AFn.java:151)
DEBUG :stacktrace     |--clojure.lang.Compiler$InvokeExpr.eval(Compiler.java:3458)
DEBUG :stacktrace     |--clojure.lang.Compiler$DefExpr.eval(Compiler.java:408)
DEBUG :stacktrace     |--clojure.lang.Compiler.eval(Compiler.java:6624)
DEBUG :stacktrace     |--clojure.lang.Compiler.eval(Compiler.java:6582)
DEBUG :stacktrace     |--clojure.core$eval.invoke(core.clj:2852)
DEBUG :stacktrace     |--clojure.main$repl$read_eval_print__6588$fn__6591.invoke(main.clj:259)
DEBUG :stacktrace     |--clojure.main$repl$read_eval_print__6588.invoke(main.clj:259)
DEBUG :stacktrace     |--clojure.main$repl$fn__6597.invoke(main.clj:277)
DEBUG :stacktrace     |--clojure.main$repl.doInvoke(main.clj:277)
DEBUG :stacktrace     |--clojure.lang.RestFn.invoke(RestFn.java:1096)
DEBUG :stacktrace     |--clojure.tools.nrepl.middleware.interruptible_eval$evaluate$fn__10235.invoke(interruptible_eval.clj:56)
DEBUG :stacktrace     |--clojure.lang.AFn.applyToHelper(AFn.java:159)
DEBUG :stacktrace     |--clojure.lang.AFn.applyTo(AFn.java:151)
DEBUG :stacktrace     |--clojure.core$apply.invoke(core.clj:617)
DEBUG :stacktrace     |--clojure.core$with_bindings_STAR_.doInvoke(core.clj:1788)
DEBUG :stacktrace     |--clojure.lang.RestFn.invoke(RestFn.java:425)
DEBUG :stacktrace     |--clojure.tools.nrepl.middleware.interruptible_eval$evaluate.invoke(interruptible_eval.clj:41)
DEBUG :stacktrace     |--clojure.tools.nrepl.middleware.interruptible_eval$interruptible_eval$fn__10276$fn__10279.invoke(interruptible_eval.clj:171)
DEBUG :stacktrace     |--clojure.core$comp$fn__4154.invoke(core.clj:2330)
DEBUG :stacktrace     |--clojure.tools.nrepl.middleware.interruptible_eval$run_next$fn__10269.invoke(interruptible_eval.clj:138)
DEBUG :stacktrace     |--clojure.lang.AFn.run(AFn.java:24)
DEBUG :stacktrace     |--java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
DEBUG :stacktrace     |--java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
DEBUG :stacktrace     |--java.lang.Thread.run(Thread.java:722)
#'taiga.core/config

I’ve added the project file.

On 15 June 2014 at 8:51:45 am, Gordon Oliver (gordon@fastnetworks.com.au) wrote:

Will try, note I'm using OSX Mavericks...

Best regards,

Gordon Oliver

On 15 Jun 2014, at 3:23 am, noisesmith notifications@github.com wrote:

can you check if you can replicate the following repl session via lein repl? :

taiga.core=> (require '[taiga.boot :as boot] '[caribou.model :as model] '[caribou.core :as caribou])
nil
taiga.core=> (def config (boot/boot))
#'taiga.core/config
taiga.core=> (caribou/with-caribou config (model/pick :model {:where {:slug "role"}}))
{:slug "role", :position 16, :display nil, :join-model false, :localized false, :name "Role", :locked true, :status-id nil, :ancestor-id nil, :searchable false, :uuid "663258ec-c2c1-4096-a4e2-d5926ed173cf", :updated-at #inst "2014-06-14T17:07:35.319000000-00:00", :created-at #inst "2014-06-14T17:07:35.286000000-00:00", :nested false, :abstract false, :id 16, :description "", :status-position 3}
taiga.core=>

**Comment by gordonro-zz** [comment]
Note I tried it on a Centos6.5 VM - works like a charm. - Must be an issue with my OSX environment.

Gordon

On 15 June 2014 at 10:38:32 am, Gordon Oliver (gordon@fastnetworks.com.au) wrote:

Hi Tried to replicate, and got this:

taiga.core=> (require '[taiga.boot :as boot] '[caribou.model :as model] '[caribou.core :as caribou])
nil
taiga.core=> (def config (boot/boot))
DEBUG :INVOKE_MODELS No models table yet!
DEBUG :stacktrace >>> org.postgresql.util.PSQLException: ERROR: relation "model" does not exist
  Position: 15
DEBUG :stacktrace     |--org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2077)
DEBUG :stacktrace     |--org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1810)
DEBUG :stacktrace     |--org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:257)
DEBUG :stacktrace     |--org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:498)
DEBUG :stacktrace     |--org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:386)
DEBUG :stacktrace     |--org.postgresql.jdbc2.AbstractJdbc2Statement.executeQuery(AbstractJdbc2Statement.java:271)
DEBUG :stacktrace     |--clojure.java.jdbc$with_query_results_STAR_.invoke(jdbc.clj:672)
DEBUG :stacktrace     |--caribou.db$query.invoke(db.clj:17)
DEBUG :stacktrace     |--caribou.db$query.invoke(db.clj:14)
DEBUG :stacktrace     |--caribou.model$invoke_models.invoke(model.clj:877)
DEBUG :stacktrace     |--caribou.core$init$fn__10721.invoke(core.clj:18)
DEBUG :stacktrace     |--clojure.java.jdbc$with_connection_STAR_.invoke(jdbc.clj:302)
DEBUG :stacktrace     |--caribou.core$init.invoke(core.clj:16)
DEBUG :stacktrace     |--taiga.boot$boot.invoke(boot.clj:49)
DEBUG :stacktrace     |--clojure.lang.AFn.applyToHelper(AFn.java:159)
DEBUG :stacktrace     |--clojure.lang.AFn.applyTo(AFn.java:151)
DEBUG :stacktrace     |--clojure.lang.Compiler$InvokeExpr.eval(Compiler.java:3458)
DEBUG :stacktrace     |--clojure.lang.Compiler$DefExpr.eval(Compiler.java:408)
DEBUG :stacktrace     |--clojure.lang.Compiler.eval(Compiler.java:6624)
DEBUG :stacktrace     |--clojure.lang.Compiler.eval(Compiler.java:6582)
DEBUG :stacktrace     |--clojure.core$eval.invoke(core.clj:2852)
DEBUG :stacktrace     |--clojure.main$repl$read_eval_print__6588$fn__6591.invoke(main.clj:259)
DEBUG :stacktrace     |--clojure.main$repl$read_eval_print__6588.invoke(main.clj:259)
DEBUG :stacktrace     |--clojure.main$repl$fn__6597.invoke(main.clj:277)
DEBUG :stacktrace     |--clojure.main$repl.doInvoke(main.clj:277)
DEBUG :stacktrace     |--clojure.lang.RestFn.invoke(RestFn.java:1096)
DEBUG :stacktrace     |--clojure.tools.nrepl.middleware.interruptible_eval$evaluate$fn__10235.invoke(interruptible_eval.clj:56)
DEBUG :stacktrace     |--clojure.lang.AFn.applyToHelper(AFn.java:159)
DEBUG :stacktrace     |--clojure.lang.AFn.applyTo(AFn.java:151)
DEBUG :stacktrace     |--clojure.core$apply.invoke(core.clj:617)
DEBUG :stacktrace     |--clojure.core$with_bindings_STAR_.doInvoke(core.clj:1788)
DEBUG :stacktrace     |--clojure.lang.RestFn.invoke(RestFn.java:425)
DEBUG :stacktrace     |--clojure.tools.nrepl.middleware.interruptible_eval$evaluate.invoke(interruptible_eval.clj:41)
DEBUG :stacktrace     |--clojure.tools.nrepl.middleware.interruptible_eval$interruptible_eval$fn__10276$fn__10279.invoke(interruptible_eval.clj:171)
DEBUG :stacktrace     |--clojure.core$comp$fn__4154.invoke(core.clj:2330)
DEBUG :stacktrace     |--clojure.tools.nrepl.middleware.interruptible_eval$run_next$fn__10269.invoke(interruptible_eval.clj:138)
DEBUG :stacktrace     |--clojure.lang.AFn.run(AFn.java:24)
DEBUG :stacktrace     |--java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
DEBUG :stacktrace     |--java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
DEBUG :stacktrace     |--java.lang.Thread.run(Thread.java:722)
#'taiga.core/config

I’ve added the project file.

On 15 June 2014 at 8:51:45 am, Gordon Oliver (gordon@fastnetworks.com.au) wrote:

Will try, note I'm using OSX Mavericks...

Best regards,

Gordon Oliver

On 15 Jun 2014, at 3:23 am, noisesmith notifications@github.com wrote:

can you check if you can replicate the following repl session via lein repl? :

taiga.core=> (require '[taiga.boot :as boot] '[caribou.model :as model] '[caribou.core :as caribou])
nil
taiga.core=> (def config (boot/boot))
#'taiga.core/config
taiga.core=> (caribou/with-caribou config (model/pick :model {:where {:slug "role"}}))
{:slug "role", :position 16, :display nil, :join-model false, :localized false, :name "Role", :locked true, :status-id nil, :ancestor-id nil, :searchable false, :uuid "663258ec-c2c1-4096-a4e2-d5926ed173cf", :updated-at #inst "2014-06-14T17:07:35.319000000-00:00", :created-at #inst "2014-06-14T17:07:35.286000000-00:00", :nested false, :abstract false, :id 16, :description "", :status-position 3}
taiga.core=>

**Comment by prismofeverything** [comment]
The error you are getting is a symptom of some failure to connect to the
database or the database not being created and set up in the first place.

Can you connect to the database directly and see what kinds of tables
exist?  Should be a handful of them, most importantly the "model" and
"field" tables.

**Comment by noisesmith** [comment]
if this is a fresh checkout as implied, the db would be the h2 file, and it was found for the migrate step

**Comment by prismofeverything** [comment]
Right, but does it have any tables in it?
